const swaggerJSDoc = require('swagger-jsdoc');

function buildOpenApiSpec({ port } = {}) {
  const spec = swaggerJSDoc({
    definition: {
      openapi: '3.0.3',
      info: {
        title: 'GSMPartsCenter API',
        version: '1.0.0',
        description:
          'Read-only REST API backed by JSON files generated by the scraper.'
      },
      servers: [
        {
          url: `http://localhost:${port || 3100}`,
          description: 'Local development'
        }
      ],
      tags: [
        { name: 'Health', description: 'Service health' },
        { name: 'Brands', description: 'Brands data' },
        { name: 'Categories', description: 'Model categories data' },
        { name: 'Models', description: 'Models data' },
        { name: 'Parts', description: 'Parts data' },
        { name: 'Search', description: 'Filtered queries' }
      ],
      components: {
        schemas: {
          Brand: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              url: { type: 'string' }
            },
            required: ['name', 'url']
          },
          Category: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              url: { type: 'string' },
              brand: { type: 'string' }
            },
            required: ['name', 'url', 'brand']
          },
          Model: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              url: { type: 'string' },
              brand: { type: 'string' },
              modelCategory: { type: 'string' }
            },
            required: ['name', 'url', 'brand', 'modelCategory']
          },
          Part: {
            type: 'object',
            properties: {
              brand: { type: 'string' },
              modelCategory: { type: 'string' },
              model: { type: 'string' },
              name: { type: 'string' },
              type: { type: 'string' },
              inStock: { type: 'boolean' },
              imageUrl: { type: 'string' },
              scrapedAt: { type: 'string', format: 'date-time' }
            },
            required: ['brand', 'modelCategory', 'model', 'name', 'type', 'inStock', 'scrapedAt']
          }
        }
      },
      paths: {
        '/health': {
          get: {
            tags: ['Health'],
            summary: 'Health check',
            responses: {
              200: {
                description: 'ok',
                content: { 'text/plain': { schema: { type: 'string', example: 'ok' } } }
              }
            }
          }
        },
        '/api/brands': {
          get: {
            tags: ['Brands'],
            summary: 'List brands',
            responses: {
              200: {
                description: 'Brands',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Brand' } }
                  }
                }
              }
            }
          }
        },
        '/api/categories': {
          get: {
            tags: ['Categories'],
            summary: 'List model categories',
            responses: {
              200: {
                description: 'Categories',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Category' } }
                  }
                }
              }
            }
          }
        },
        '/api/models': {
          get: {
            tags: ['Models'],
            summary: 'List models',
            responses: {
              200: {
                description: 'Models',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Model' } }
                  }
                }
              }
            }
          }
        },
        '/api/parts': {
          get: {
            tags: ['Parts'],
            summary: 'List parts',
            responses: {
              200: {
                description: 'Parts',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Part' } }
                  }
                }
              }
            }
          }
        },
        '/api/search/parts': {
          get: {
            tags: ['Search'],
            summary: 'Search parts by filters',
            parameters: [
              { name: 'brand', in: 'query', schema: { type: 'string' } },
              { name: 'modelCategory', in: 'query', schema: { type: 'string' } },
              { name: 'model', in: 'query', schema: { type: 'string' } },
              { name: 'type', in: 'query', schema: { type: 'string' } },
              { name: 'inStock', in: 'query', schema: { type: 'boolean' }, description: 'true/false' }
            ],
            responses: {
              200: {
                description: 'Filtered parts',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Part' } }
                  }
                }
              }
            }
          }
        },
        '/api/search/models': {
          get: {
            tags: ['Search'],
            summary: 'Search models by filters',
            parameters: [
              { name: 'brand', in: 'query', schema: { type: 'string' } },
              { name: 'modelCategory', in: 'query', schema: { type: 'string' } },
              { name: 'name', in: 'query', schema: { type: 'string' } }
            ],
            responses: {
              200: {
                description: 'Filtered models',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Model' } }
                  }
                }
              }
            }
          }
        },
        '/api/search/categories': {
          get: {
            tags: ['Search'],
            summary: 'Search categories by filters',
            parameters: [
              { name: 'brand', in: 'query', schema: { type: 'string' } },
              { name: 'name', in: 'query', schema: { type: 'string' } }
            ],
            responses: {
              200: {
                description: 'Filtered categories',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Category' } }
                  }
                }
              }
            }
          }
        },
        '/api/search/brands': {
          get: {
            tags: ['Search'],
            summary: 'Search brands by name',
            parameters: [{ name: 'name', in: 'query', schema: { type: 'string' } }],
            responses: {
              200: {
                description: 'Filtered brands',
                content: {
                  'application/json': {
                    schema: { type: 'array', items: { $ref: '#/components/schemas/Brand' } }
                  }
                }
              }
            }
          }
        }
      }
    },
    apis: []
  });

  return spec;
}

module.exports = { buildOpenApiSpec };

